fileVersion: 1
id: "2"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: BEN_EDW
    schema: 7.1_Regression_ENV
name: 7.1 Regression Environment
type: Environment
