fileVersion: 1
id: "3"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: RAINFOREST_SAMPLE
  WORK:
    database: BEN_EDW
    schema: RBAC_ENV1
name: New Environment
type: Environment
